__title__ = "prousthon"
__description__ = "Package to generate Proust-related questions"
__url__ = "https://github.com/deepspaceghost/deme-app/tree/prousthon"
__version__ = "0.0.0.150"
__author__ = "deepspaceghost"
__author_email__ = "ghostblac@protonmail.com"
__license__ = "none"
__copyright__ = "© 2021 demiurge"
