__title__ = "gamedex"
__description__ = "Package to generate video games"
__url__ = "https://github.com/deepspaceghost/deme-app/tree/gamedex"
__version__ = "0.0.0.150"
__author__ = "deepspaceghost"
__author_email__ = "ghostblac@protonmail.com"
__license__ = "none"
__copyright__ = "© 2021 demiurge"
